version: "3.7"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/var/www"
    ports:
      - "80:80"
      - "433:433"
    #container_name: nginx
    #restart: always
    environment:
      - NGINX_HOST=tegar.test
    networks:
      - app-network

  app:
    #container_name: laravel
    build:
      context: "./"
      dockerfile: "./dev.dockerfile"
    #restart: always
    volumes:
      - "./src:/var/www"
    networks:
      - app-network

  mysql:
    image: mariadb:10.4.8
    #container_name: mysql
    ports:
      - "3306:3306"
    #restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    #container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
